### ISSUE TITLE
[Request] Kindly request new functionalities

### ISSUE THREAD

**Issue by PunnyBunny1** [ColormaticStudios/quality-godot-first-person#1]
Hello,

I would like to request these new functionalities:

- **Sneak**/**Crouch Walk**
- **Crawl** 
- **Speed increment** (Pressing and holding the key for run, gradually accelerates the player's running speed, intensifying the sense of vulnerability and immersion in the the game, like in Outlast 2)
- **Stamina/Fatigue** (Over time, running at maximum speed could cause the player character to become tired, which might result in slower movement or other negative effects.)

Thank you!

**Comment by ColormaticStudios** [comment]
I think stamina/fatigue would add too much complexity to the base system, so I will make a separate patch type thing to add that to decrease bloat (some games don't have a stamina system and just let you run infinitely) but sneak, crawl, and speed increment are good things to add to the base.
